baseURL = "https://seclab.netlify.com/"
languageCode = "en-us"
title = "SecLab"


[permalinks]
  blog = "/blog/:filename/"

# See https://feathericons.com/
# The value of pre is the icon name
[menu]
  [[menu.main]]
    name = "Sponsors"
    pre = "git-commit"
    url = "/sponsors/"
    weight = 2
  [[menu.main]]
    name = "Publications"
    pre = "book-open"
    url = "/publications/"
    weight = 3
  [[menu.main]]
    name = "People"
    pre = "users"
    url = "/people/"
    weight = 3
  [[menu.sub]]
    name = "Blog"
    pre = "edit"
    url = "/blog/"
    weight = 5
  [[menu.sub]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 4

[sponsor]
  [[sponsor.list]]
    short = "ARL"
    name = "Army Research Laboratory"
    url = "http://www.arl.army.mil/"
  [[sponsor.list]]
    short = "ARO"
    name = "Army Research Office"
    url = "https://www.aro.army.mil"
  [[sponsor.list]]
    short = "DARPA"
    name = "Defense Advanced Research Projects Agency"
    url = "http://www.darpa.mil/"

[params]
  homeText = "The Computer Security Group at UCSB works on tools and techniques for designing, building, and validating secure software systems. The group's research focus is on intrusion detection and correlation, vulnerability analysis, malware detection and containment, and security of web-based applications."
 profile = '/img/profile.png'
