baseURL = "https://seclab.netlify.com/"
languageCode = "en-us"
title = "SecLab"


[permalinks]
  blog = "/blog/:filename/"

# See https://feathericons.com/
# The value of pre is the icon name
[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Sponsors"
    pre = "edit"
    url = "/sponsors/"
    weight = 2
  [[menu.main]]
    name = "Publications"
    pre = "edit"
    url = "/publications/"
    weight = 3
  [[menu.main]]
    name = "People"
    pre = "edit"
    url = "/people/"
    weight = 3
  [[menu.sub]]
    name = "Blog"
    pre = "edit"
    url = "/blog/"
    weight = 5
  [[menu.sub]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 4

[params]
  homeText = "The Computer Security Group at UCSB works on tools and techniques for designing, building, and validating secure software systems. The group's research focus is on intrusion detection and correlation, vulnerability analysis, malware detection and containment, and security of web-based applications."
